[package]
name = "coincap_exchange"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive", "env"] }
duckdb = { version = "1.4.4", features = ["bundled"] }
env_logger = "0.11.9"
log = "0.4.29"
